### ISSUE TITLE
Can't compile using gcc 7.1

### ISSUE THREAD

**Issue by xoac** [richfelker/musl-cross-make#31]
Hi,

I can't compile toolchain using g++ 7.1

Here is an error:
```
../../src_toolchain/gcc/ubsan.c: In function ‘bool ubsan_use_new_style_p(location_t)’:
../../src_toolchain/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       || xloc.file == '\0' || xloc.file[0] == '\xff'
```
And my g++ configuration:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 7.1.1 20170528 (GCC) 
```

**Comment by rain-1** [comment]
I got this same error

**Comment by osvein** [comment]
Fixed by 48d9c59d22d16e8898a4d851759d00002d9926c4

**Comment by xoac** [comment]
I will close it for now and try compile when have more time. Thx.
